models/category.py
import time
from models import Model
from models.MyMongo import MyMongo
from models.mysql import myMysql

class Category(Model):
    def __init__(self, form):
        self.id = None
        self.title = form.get('title', '')
        self.ct = int(time.time())
        self.ut = self.ct


# class Category(MyMongo):
#     __fields__ = MyMongo.__fields__ +[
#         ('title', str, ''),
#     ]


# class Category(myMysql):
#     fields = myMysql.fields+[
#         'title',
#     ]

routes/category.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)


from models.category import (
    Category,
)
from models.page import Page


main = Blueprint('category', __name__)


@main.route("/<string:category>")
def index(category):
    ps = Page.find_all(category = category)
    return render_template('category.html',pageData = ps,categorys = Category.all())

routes/index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
)
from models.page import Page
from models.category import Category
from utils import log

main = Blueprint('index', __name__)


@main.route("/")
def index():
    # form = {'title':'素颜韵脚'}
    # Category.new(form)
    ps = Page.all(page = 1)
    cs = Category.all()
    return render_template("index.html",pageData = ps,categorys = cs)


@main.route("/list", methods=['POST'])
def more():
    page = int(request.values['page'])
    size = int(request.values['size'])
    res = Page.all(page,size)
    return render_template("page-item.html", pageData=res)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    m = Page.new(form)
    return redirect(url_for('page.detail',id=m.id))


@main.route("/new")
def new():
    cs = Category.all()
    return render_template("new.html",cs = cs)

routes/page.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)


from models.page import (
    Page,

)


main = Blueprint('page', __name__)


@main.route('/<int:id>')
def detail(id):
    m = Page.get(id)
    return render_template("detail.html", page=m)

templates/category.html
{% extends "index.html" %}
{% block content %}
<ul class="blog-content-wrappper" id="blogContent">
  {% for p in pageData %}
    <li class="blog-content-item">
      <h3 class="blog-content-title"><a href="{{ url_for('page.detail', id=p.id) }}">{{p.title}}</a></h3>
      <div class="blog-content-desc">
        <p>{{p.desc}}</p>
        <a class="blog-content-more" href="{{ url_for('page.detail', id=p.id) }}">阅读更多</a>
      </div>
      <div class="blog-content-info">
        <span class="blog-content-author">作者：{{p.author}}</span>
        <span>&nbsp;&nbsp;|&nbsp;&nbsp;</span>
        <span class="blog-content-comment">分类：{{p.category}}</span>
      </div>
    </li>
  {% endfor %}
</ul>
{% endblock %}
{% block more %}
{% endblock %}

templates/detail.html
{% extends "index.html" %}
  {% block title %}
    <title>{{page.title}} | degebug.com 博客</title>
  {% endblock %}
  {% block link %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/common.css',_external=True) }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/detail.css',_external=True) }}">
  {% endblock %}
  {% block container %}
    <div class="blog-page">
      <h2 class="blog-page-title">{{page.title}}</h2>
      <div class="blog-page-info">
          <span class="blog-page-author">作者：{{page.author}}</span>
          <span>&nbsp;&nbsp;|&nbsp;&nbsp;</span>
          <span class='blog-page-comment'>分类：<a href="{{ url_for('category.index', category=page.category) }}">{{page.category}}</a></span>
      </div>
      <div class="blog-page-content"name="content">
        {{ page.content|neomarkdown }}
      </div>
    </div>
    <aside class="blog-top" id="blogTop">Top</aside>
  {% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="description" content="degebug.com是一个开发者的博客，在这里，你将...等一下，我de个bug先！">
  <meta name="keywords" content="degebug.com,博客,技术,程序员,debug,前端,日记,写作,阅读,原创,吴晓坚">
  <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static',filename='/img/blog-favicon.ico',_external=True) }}">
  {%block title%}
    <title>wuxiao 博客</title>
  {% endblock %}
  <link href="https://cdn.bootcss.com/normalize/8.0.1/normalize.css" rel="stylesheet">
  {% block link %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/common.css',_external=True) }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/home.css',_external=True) }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/page-item.css',_external=True) }}">
  {% endblock %}
</head>
<body>
  <header class="blog-header">
    <h1 class="blog-logo"><a href="/">degebug.com 博客</a></h1>
    <nav class="blog-nav">
      <a class="blog-nav-item" href="/">首页</a>
      <a class="blog-nav-item" href="/" target="_blank">关于我</a>
      <a class="blog-nav-item" href="{{ url_for('index.new') }}">发博客</a>
      <!-- <a class="blog-nav-item" href="//admin.degebug.com" target="_blank">博客管理</a> -->
    </nav>
  </header>
  <div class="blog-container">
    {%block container%}
      <section class="blog-category">
        <h2 class="blog-category-title">分类目录</h2>
        <ul class="blog-category-list">
            {% for c in categorys %}
              <li><a href="{{ url_for('category.index',category = c.title) }}">{{c.title}}</a></li>
            {% endfor %}
        </ul>
      </section>
      <section class="blog-content">
        {% block content %}
          <ul class="blog-content-wrappper" id="blogContent">
              {% for p in pageData %}
                <li class="blog-content-item">
                  <h3 class="blog-content-title"><a href="{{ url_for('page.detail', id=p.id) }}">{{p.title}}</a></h3>
                  <div class="blog-content-desc">
                    <p>{{p.desc}}</p>
                    <a class="blog-content-more" href="{{ url_for('page.detail', id=p.id) }}">阅读更多</a>
                  </div>
                  <div class="blog-content-info">
                    <span class="blog-content-author">作者：{{p.author}}</span>
                    <span>&nbsp;&nbsp;|&nbsp;&nbsp;</span>
                    <span class="blog-content-comment">分类：{{p.category}}</span>
                  </div>
                </li>
              {% endfor %}
            </ul>
        {% endblock %}
        {% block more %}
        <div class="blog-more" id="blogMore" data-page="2" data-size="5">更多文章</div>
        {% endblock %}
      </section>
      <aside class="blog-top" id="blogTop">Top</aside>
    {% endblock %}
  </div>
  <footer class="blog-footer">
    <p>Copyright&copy;2018-2019 吴晓坚 版权所有</p>
    <p><a target="_blank" rel="noopener noreferrer" href="http://www.miitbeian.gov.cn">粤ICP备18084360号-1</a></p>
  </footer>
</body>
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script src="{{ url_for('static',filename='js/index.js',_external=True) }}"></script>
<script>
  [#$("div[name='content']").each(function(){
      var text = $(this).html();
      var reg = new RegExp('\n','g');
      $(this).html(text.replace(reg,'<br/>'));
      });#]
</script>
</html>

templates/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>发表博客文章</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.min.css',_external=True) }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/style.css',_external=True) }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='lib/editor/editor.css',_external=True) }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='lib/webuploader/webuploader.css',_external=True) }}">
    <script src="{{ url_for('static',filename='lib/jquery-3.0.0.min.js',_external=True) }}"></script>
    <script src="{{ url_for('static',filename='lib/markdownit.js',_external=True) }}"></script>
    <script src="{{ url_for('static',filename='lib/webuploader/webuploader.withoutimage.js',_external=True) }}"></script>
    <script src="{{ url_for('static',filename='lib/editor/editor.js',_external=True) }}"></script>
    <script src="{{ url_for('static',filename='lib/editor/ext.js',_external=True) }}"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
<form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
    <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
        <div>
            <textarea class='span5' id='desc'
                  name='desc' rows='1'
                  placeholder="一句话概括全文"></textarea>
            <textarea class='span3' id='author'
                  name='author' rows='1'
                  placeholder="作者"></textarea>
        </div>
        <span class="tab-selector">选择版块：</span>
        <select name="category" id="category" required>
            <option value="">请选择分类</option>
                {% for c in cs %}
                <option value="{{ c.title }}">{{ c.title }}</option>
                {% endfor %}
        </select>
        <div class='markdown_editor in_editor'>
          <div class='markdown_in_editor'>
            <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
            <div class='editor_buttons'>
              <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
            </div>
          </div>
        </div>
    </fieldset>
</form>
                </div>
            </div>
        </div>
    </div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>

templates/page-item.html
{% for p in pageData %}
  <li class="blog-content-item">
    <h3 class="blog-content-title"><a href="{{ url_for('page.detail', id=p.id) }}">{{p.title}}</a></h3>
    <div class="blog-content-desc">
      <p>{{p.desc}}</p>
      <a class="blog-content-more" href="{{ url_for('page.detail', id=p.id) }}">阅读更多</a>
    </div>
    <div class="blog-content-info">
      <span class="blog-content-author">作者：{{p.author}}</span>
      <span>&nbsp;&nbsp;|&nbsp;&nbsp;</span>
      <span class="blog-content-comment">分类：{{p.category}}</span>
    </div>
  </li>
{% endfor %}